# Generated by Django 3.0.3 on 2020-03-15 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Country ID')),
                ('name', models.CharField(max_length=100, verbose_name='Country Name')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Province ID')),
                ('name', models.CharField(max_length=100, verbose_name='Province Name')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual.Country')),
            ],
        ),
        migrations.CreateModel(
            name='CovidObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_num', models.IntegerField(verbose_name='Serial Number')),
                ('observation_date', models.DateTimeField(verbose_name='Observation Date')),
                ('last_update', models.DateTimeField(verbose_name='Last Update')),
                ('confirmed_case', models.IntegerField(verbose_name='Confirmed Cases')),
                ('death_case', models.IntegerField(verbose_name='Death Cases')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual.Country')),
                ('province_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visual.Province')),
            ],
        ),
    ]
