# Generated by Django 3.0.3 on 2020-03-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='province',
            old_name='question',
            new_name='country',
        ),
    ]
